with open('secondTry.txt') as f:
    tempDeck = eval(f.readline())
    discardPile = eval(f.readline())
    c1 = eval(f.readline())
    c2 = eval(f.readline())
    c3 = eval(f.readline())
    c4 = eval(f.readline())
    p1m = int(f.readline())
    p2m = int(f.readline())
    p3m = int(f.readline())
    p4m = int(f.readline())
    p2d = int(f.readline())
    p3d = int(f.readline())
    p4d = int(f.readline())
    temp2 = f.readline()
    P2playersCards = eval(temp2)
    temp3 = f.readline()
    P3playersCards = eval(temp3)
    temp4 = f.readline()
    P4playersCards = eval(temp4)




print(f"tempDeck: {tempDeck}")
print(f"discardPile: {discardPile}")


print(f"c1: {c1}")
print(f"c2: {c2}")
print(f"c3: {c3}")
print(f"c4: {c4}")

p2d =int(p2d)
p3d =int(p3d)
p4d =int(p4d)
print(f"p2d: {p2d}")
print(f"p3d: {p3d}")
print(f"p4d: {p4d}")

print(f"type: {type(P2playersCards)}")
print(f"P2playersCards: {P2playersCards}")
print(f"type: {type(P3playersCards)}")
print(f"P3playersCards: {P3playersCards}")
print(f"type: {type(P4playersCards)}")
print(f"P4playersCards: {P4playersCards}")

newGameFileName = input("what do you want to save the game file as: ")
f = open(f"{newGameFileName}.txt", "w")
f.write(str([('10', 'spades'), ('10', 'heart'), ('Jack', 'diamonds'), ('4', 'diamonds'), ('3', 'clubs'), ('2', 'heart'), ('3', 'diamonds'), ('4', 'clubs'), ('3', 'heart'), ('Jack', 'clubs'), ('2', 'diamonds'), ('Jack', 'spades'), ('9', 'diamonds'), ('9', 'clubs'), ('4', 'spades'), ('8', 'diamonds'), ('Ace', 'heart'), ('Ace', 'diamonds'), ('8', 'clubs'), ('10', 'clubs'), ('Ace', 'spades'), ('5', 'diamonds'), ('8', 'heart'), ('King', 'diamonds'), ('7', 'heart'), ('6', 'heart'), ('6', 'clubs'), ('6', 'diamonds'), ('5', 'heart'), ('Queen', 'clubs'), ('7', 'spades'), ('10', 'diamonds'), ('9', 'spades')]))
f.write("\n")
f.write(str([('5', 'spades'), ('2', 'spades'), ('Queen', 'diamonds')]))
f.write("\n")
f.write(str([('4', 'heart'), ('2', 'clubs'), ('King','clubs'), ('Jack','heart')]))
f.write("\n")
f.write(str([('5', 'clubs'),('King', 'heart'), ('Ace','clubs'), ('King','spades')]))
f.write("\n")
f.write(str([('3', 'spades'),('7', 'diamonds'), ('7','clubs'), ('Queen','spades')]))
f.write("\n")
f.write(str([('9', 'heart'),('8', 'spades'), ('Queen','heart'), ('6','spades')]))
f.write("\n")
f.write(str(0))
f.write("\n")
f.write(str(0))
f.write("\n")
f.write(str(0))
f.write("\n")
f.write(str(0))
f.write("\n")
f.write(str(1))
f.write("\n")
f.write(str(2))
f.write("\n")
f.write(str(3))
f.write("\n")
f.write(str({"players": {"player1":{"card1":(None,None), "card2":(None,None), "card3":(None,None), "card4":(None,None)}, "player3":{"card1":(None,None), "card2":(None,None), "card3":(None,None), "card4":(None,None)}, "player4":{"card1":(None,None), "card2":(None,None), "card3":(None,None), "card4":(None,None)}}}))
f.write("\n")
f.write(str({"players": {"player1":{"card1":(None,None), "card2":(None,None), "card3":(None,None), "card4":(None,None)}, "player3":{"card1":(None,None), "card2":(None,None), "card3":(None,None), "card4":(None,None)}, "player4":{"card1":(None,None), "card2":(None,None), "card3":(None,None), "card4":(None,None)}}}))
f.write("\n")
f.write(str({"players": {"player1":{"card1":(None,None), "card2":(None,None), "card3":(None,None), "card4":(None,None)}, "player3":{"card1":(None,None), "card2":(None,None), "card3":(None,None), "card4":(None,None)}, "player4":{"card1":(None,None), "card2":(None,None), "card3":(None,None), "card4":(None,None)}}}))
f.close()          
"""